### PR TITLE
Display biolucida images in gallery based on scicrunch

### PR DESCRIPTION
**Pull request by ddjnw1yu**
For sprint ticket - [Bug Submission: Image viewer not opening](https://www.wrike.com/open.htm?id=1363738055)

This should help to hide the biolucida image whose id does not exist in Scicrunch.

### CODE REVIEW

**Review by egauzens — DISMISSED** [review]
I don't think this is right since there does appear to be images for those gallery items, for example:

https://sparc.science/datasets/file/287/1?path=files/derivative/MicroCT-and-Segmentation/sub-pig-2/Nerve-2-Segmentation-Files/22_2.jpx

**Comment by egauzens** [comment]
> I don't think this is right since there does appear to be images for those gallery items, for example:
> 
> https://sparc.science/datasets/file/287/1?path=files/derivative/MicroCT-and-Segmentation/sub-pig-2/Nerve-2-Segmentation-Files/22_2.jpx

Ah nvm I just read the comments you posted on the Wrike ticket. So ideally once scicrunch has been updated then the images would show again in the gallery, correct?

**Comment by ddjnw1yu** [comment]
> > I don't think this is right since there does appear to be images for those gallery items, for example:
> > https://sparc.science/datasets/file/287/1?path=files/derivative/MicroCT-and-Segmentation/sub-pig-2/Nerve-2-Segmentation-Files/22_2.jpx
> 
> Ah nvm I just read the comments you posted on the Wrike ticket. So ideally once scicrunch has been updated then the images would show again in the gallery, correct?

Yes, that's right. As long as related Biolucida metadata is updated in Scicrunch metadata, images will show again. The function still uses the Biolucida data to generate gallery image items. Just added one more filtering step to check if these images exist on Scicrunch.

**Comment by alan-wu** [comment]
@ddjnw1yu A more complete solution is to use the Scicrunch response itself to build up all the biolucida image items on the gallery instead of making an extra call with `biolucida.searchDataset`. It will be similar to theway scaffold, flatmap and plot item are populate but only include biolucida2d/biolucida3d items with a biolucida id.

**Comment by alan-wu** [comment]
@egauzens FYI, some datasets have a lot of biolucida images and not all of them are intended to be viewed on the Portal so the presence of a biolucida id gives us an idea of which biolucida images should be present/highlighted on the gallery.

**Comment by ddjnw1yu** [comment]
> @ddjnw1yu A more complete solution is to use the Scicrunch response itself to build up all the biolucida image items on the gallery instead of making an extra call with `biolucida.searchDataset`. It will be similar to theway scaffold, flatmap and plot item are populate but only include biolucida2d/biolucida3d items with a biolucida id.

I have taken a look at the code and had a try. We probably shouldn't do this. From what I saw, we will still need to call `biolucida.searchDataset` because some required information does not exist on Scicrunch. Sometimes, Scicrunch may have hundreds of biolucida objects, which could make things more complicated.

**Comment by ddjnw1yu** [comment]
The latest commit uses Scicrunch data to create gallery items.

**Pull request merged**
