### PR TITLE
E2E testing setup for nuxt3 portal

### PR DESCRIPTION
**Pull request by ddjnw1yu**
Portal environment variables need to be added to `secrets`.

General tests are migrated from the nuxt2 portal to the nuxt3 portal.

- Updated selectors
- Fixed bugs
- Created a new yaml file to trigger testing for PR, schedule, and manual

examples for the new yaml file

- PR - [github action](https://github.com/ddjnw1yu/sparc-app-2/actions/runs/8887640868), [cypress result](https://cloud.cypress.io/projects/jwe8mn/runs/80/overview?roarHideRunsWithDiffGroupsAndTags=1)
- Schedule - [github action](https://github.com/ddjnw1yu/sparc-app-2/actions/runs/8886392595), [cypress result](https://cloud.cypress.io/projects/jwe8mn/runs/74/overview?roarHideRunsWithDiffGroupsAndTags=1)
- Manual - [github action](https://github.com/ddjnw1yu/sparc-app-2/actions/runs/8887466608), [cypress result](https://cloud.cypress.io/projects/jwe8mn/runs/79/overview?roarHideRunsWithDiffGroupsAndTags=1)

### CODE REVIEW

**Review by alan-wu — COMMENTED** [review]
Is the MarkdownTest used anywhere?

**Comment by ddjnw1yu** [comment]
> Is the MarkdownTest used anywhere?

No, it was originally there in nuxt2. It looks like someone created that 4 years ago. Let me know if I need to delete it.

**Comment by alan-wu** [comment]
> > Is the MarkdownTest used anywhere?
> 
> Not in nuxt3 at the moment. Someone created that 4 years ago in nuxt 2. Let me know if I should remove it.

We should delete it, there is no command to run it.

**Review by alan-wu — APPROVED** [review]
Thanks, look good to me.

**Pull request merged**
